name: oretgen
description: OpenApi 3 to retrofit dart venerator.
version: 0.0.1
homepage: https://github.com/baik78/openapi-to-rerofitdart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.4
  yaml: ^2.2.0
  args: ^1.6.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.2
